name: ModeratorCore
version: 1.5
api: 3.0.0
main: Core\Main

commands:
  tpall:
    description: "§f[§3ModeratorCore§f]§r > Teleport the entire server to you"
    usage: "/tpall [string:message]"
    permission: "modore.tpall"

  gm1:
    description: "§f[§3ModeratorCore§f]§r > Gamemode Creative"
    usage: "/gm1"
    permission: "modore.gm1"


  gm2:
    description: "§f[§3ModeratorCore§f]§r > Gamemode Adventure"
    usage: "/gm2"
    permission: "modore.gm2"

  gm3:
    description: "§f[§3ModeratorCore§f]§r > Gamemode Spectator"
    usage: "/gm3"
    permission: "modore.gm3"

  gm0:
    description: "§f[§3ModeratorCore§f]§r > Gamemode Survival"
    usage: "/gm0"
    permission: "modore.gm0"

  vanish:
    description: "§f[§3ModeratorCore§f]§r > Enable vanish to be invisible"
    usage: "/vanish"
    permission: "modore.vanish"

  kickall:
    description: "§f[§3ModeratorCore§f]§r > Kick all players this server"
    usage: "/kickall [string:message]"
    permission: "modore.kickall"

  announce:
    description: "§f[§3ModeratorCore§f]§r > Make an announcement"
    usage: "/annonce [string:message]"
    permission: "modcore.annonce"
# PLAYER COMMANDS

  feed:
    description: "§f[§3PlayerCore§f]§r > Eating is Important!"
    usage: "/feed"
    permission: "modcore.feed"
    
  heal:
    description: "§f[§3PlayerCore§f]§r > We must heal!"
    usage: "/heal"
    permission: "modcore.heal"
    
  xyz:
    description: "§f[§3PlayerCore§f]§r > Know your coordinates"
    usage: "/xyz"


permissions:
 modore.gm1:
  default: op
 modore.gm2:
  default: op
 modore.gm3:
  default: op
 modore.gm0:
  default: op
 modcore.heal:
  default: op
 modcore.feed:
  default: op
